# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: parsing pkg CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'parsing/**'
      - '.github/workflows/parsing.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'parsing/**'
      - '.github/workflows/parsing.yml'

env:
  WORKING_DIRECTORY: ./parsing

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Test
      run: go test -v ./...
      
    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
        working-directory: ${{ env.WORKING_DIRECTORY }}
